package com.dd3boh.outertune.transition.model

/**
 * The immutable blueprint for a transition.
 *
 * This class MUST be pure and serializable-friendly.
 * It contains exactly enough information to reproduce a transition audio-visually
 * without needing to re-analyze waveforms or re-calculate BPMs.
 *
 * Generated by: TransitionMath
 * Consumed by: TransitionPlaybackEngine, Database (via conversion)
 */
data class TransitionPlan(
    // --- Synchronization ---
    /**
     * Playback speed multiplier for Track B to match Track A.
     * e.g., 1.02 means Track B plays 2% faster.
     */
    val initialSpeedB: Double,

    /**
     * Grid compression factor for Track B's interval matching.
     * Used when we match beats by interval rather than strict tempo.
     * 1.0 = strict tempo match.
     */
    val gridScalarB: Double,

    // --- Beat Alignment (Relative) ---
    /**
     * The beat index on Track A where the transition zone (Green Box) starts.
     * Corresponds to 0.0 progress in the mixer.
     */
    val anchorBeatA: Double,

    /**
     * The beat index on Track B where the transition zone starts.
     * Note: This is the "internal" beat index, possibly adjusted by gridScalarB.
     */
    val anchorBeatB: Double,

    /**
     * The duration of the transition zone in beats (e.g., 16.0 for 4 bars).
     */
    val transitionDurationBeats: Double,

    // --- Absolute Timestamps (For Saving / Seeking) ---
    /**
     * Exact timestamp (ms) on Track A where the transition starts (Anchor A).
     */
    val exitPointMs: Long,

    /**
     * Exact timestamp (ms) on Track B where the transition starts (Anchor B).
     */
    val entryPointMs: Long,

    /**
     * The calculated duration of the transition in milliseconds,
     * based on Track A's grid speed at the anchor point.
     */
    val durationMs: Long,

    // --- Raw Data (Required for Real-time PLL) ---
    /**
     * High-precision beat grid for Track A.
     */
    val gridA: List<Double>,

    /**
     * High-precision beat grid for Track B.
     */
    val gridB: List<Double>
)

/**
 * Configuration for the creative aspects of the mix.
 * These are user-editable settings that do not affect the fundamental synchronization
 * but dictate how the audio engine processes the crossfade.
 */
data class TransitionConfig(
    val overlapMode: String = "Overlap", // "Crossfade", "Cut", etc.
    val eqMode: String = "None",         // "Bass Swap", etc.
    val effectMode: String = "None",     // "Low Pass In", etc.
    val barsCount: Int = 4,
    val widthFraction: Float = 0.75f     // Visual width of the transition zone (0.0 - 1.0)
)